export const Colleges = [
  'Shri Vaishnav Vidyapeeth Vishwavidyalaya (SVVV)',
  'BM College of Pharmaceutical Education and Research',
  'Chordia Institute of Pharmacy',
  'Indore Institute of Pharmacy',
  'Modern Institute of Pharmaceutical Sciences',
  'Oriental College of Pharmacy and Research',
  'RKDF Institute of Pharmaceutical Sciences',
  'Shri Gujrati Samaj College of Pharmacy',
  'Safe Institute of Pharmacy',
  'Shri Bherulal Pharmacy Institute',
  'Acropolis Institute of Technology and Research',
  'Barli Vocational Institute for Rural Women (BVIRW)',
  'Central India Institute of Technology (CIIT)',
  'Centre for Advanced Technology',
  'Christian Eminent Academy (CEA)',
  'Daly College Businesss School',
  'Government Maharani Laxmi Bai Girls PG College',
  'Govindram Seksaria Institute of Management and Research (GSIMR)',
  'Government Holkar Science College',
  'Indian Institute of Management (IIM)',
  'Indore Indira School of Career Studies (IISCS)',
  'Indore Professional Studies Academy (IPSA)',
  'Indore School of Social Work (ISSW)',
  'Institute of Environmental Planning and Technology - School of Architecture',
  'International Institute of Foreign Trade and Research (IIFTR)',
  'International Institute of Professional Studies (IIPS)',
  'IPS School of Architecture',
  'IPS Academy of Hotel Management and Catering Technology',
  'Islamia Karimia College',
  'Kasturba Gram Rural Institute',
  'MB Khalsa College',
  'Maharaja Ranjit Singh College of Professional Sciences',
  'Medi-Caps Institute of Technology and Management',
  'PMB Gujarati Commerce College',
  'Pioneer Institute of Professional Studies',
  'PMB Gujarati Science College',
  'Prestige Institute of Management And Research',
  'Rishiraj Institute of Technology (RIT)',
  'Sanghvi Institute of Management and Science (SIMS)',
  'School of Computer Science',
  'Shri Cloth Market Kanya Vanijya Mahavidyalaya',
  'Shri RGP Gujrati Professional Institute',
  'Shri Vaishnav College of Commerce',
  'Shri Vaishnav Institute of Management, Indore (SVIMI)',
  'Shri Vaishnav Institute of Technology and Science (SVITS)',
  'Shri Vaishnav Polytechnic, Indore',
  'MKHS Gujarati Girls College',
  'Small Industries Service Institute (SISI)',
  'Smriti College of Pharmaceutical Education (SCOPE)',
  'Sushila Devi Bansal College of Technology (SDBCT)',
  'Swati Jain College (SJC)',
  'Truba College of Engineering and Technology',
  'PT Education',
  'Career Forum',
  'Career Makers',
  'Career Udaan',
  'Disha Consultancy',
  'Influx Services',
  'Kaivalayam Technologies Pvt Ltd',
  'Manpower Marketing Service',
  'Lakshya Institute of Profesional Studies',
  'SAGE University',
  'Devi Ahilya Vishwavidyalaya',
  'Madhya Pradesh Public Service Commission',
  'Indian Business School (IBS), Indore Campus',
  'Government Arts and Commerce College',
  'Indore Christian College',
  'Indore Institute of Law',
  'Shri Vaishnav Institute of Law',
  'Guru Gobind Singh Law College',
  'MB Khalsa Law College',
  'School of Law, Devi Ahilya Viswa Vidyalaya',
  'Christian Eminent Academy of Management, Professional Education and Research',
  'SDPS Womens College College of Architecture',
  'College of Dental Sciences and Hospital',
  'Sri Aurobindo College of Dentistry',
  'Index Medical College Hospital and Research Centre',
  'MGM Medical College',
  'Shri Aurobindo Institute of Medical Sciences',
  'Government College of Dentistry',
  'Modern Dental College and Research Centre',
  'Choithram Hospital and Research Centre (CHandRC), Choithram College of Nursing',
  'College of Nursing',
  'Index Group of Institutions',
  'Index Institute of Dental Sciences',
  'Malwanchal University',
  'Government Law College',
  'Shri Saibaba College For Teachers Training',
  'Shri Vaishnav College Of Teachers Training',
  'Shri Yashwant Singh B Ed College',
  'Shubh Deep Shikshan Sansthan',
  'Arts and Commerce College',
  'BR Nahata Smriti College Of Pharmacy',
  'BY SHRI OM SHANTI Education Societys Gyan Shiksha Mahavidyalaya',
  'Comp-Feeders Takniki Prashikshan Sanstha',
  'Devi Ahilya College of Pharmacy',
  'Government Ashtang Ayurved College and Hospital',
  'Indore Institute Of Technology and Management',
  'Indore Mahavidyalaya',
  'Institute Of Engineering and Sciences',
  'Institute Of Engineering and Technology',
  'IPS Academy College of Pharmacy',
  'Ips Academy Institute of Business Management and Research',
  'Ishak Patel Women Teachers Training College',
  'Lakshmi Narain College Of Technology',
  'Lalit Kala Sansthan',
  'Malwa Institute Of Technology',
  'Matushri Ahilya Devi Teachers Education Institute',
  'MB Khalsa Institution Of Education',
  'Music College',
  'New Girls Degree College',
  'New Science College',
  'Nutan Shikshan Samiti Sanchalit',
  'Parijat College',
  'Government Girls Degree College',
  'Rajiv Gandhi Homoeopathic Medical College Hospital and Research Centre',
  'RD Memorial College Of Physical Education',
  'Sanskrit College',
  'Shiv Kumar Singh College Of Professional Studies',
  'Shree Gujarati Samaj Homoeopathic Medical College Hospital and Research Centre',
  'Shri GS Seksaria Institute of Technology and Science (SGSITS)',
  'Shri Gujarati Samaj',
  'Shri Gujarati Samaj Institute Of Professional Studies (SGSIPS)',
  'Shri Jain Diwakar Mahavidyalaya',
  'Shri Jain Swetamber Professional Academy',
  'Smt Dhairya Prabha Devi Sajatia Womens',
  'Swami Vivekanand College Of Engineering',
  'Swami Vivekanand College Of Pharmacy',
  'Yogeshwar Shiksha Mahavidyalaya',
  'Sushila Devi Bansal College of Engineering (SDBCE)',
  'Jaipuria Institute of Management',
  'Indian Institute of Technology',
  'Indore Institute of Science and Technology',
  'Sanghvi Institute of Technology',
  'International Institute of Engineering and Science',
  'Malwa Institute of Science and Technology MITS',
  'Police Training School',
  'Government Fine Arts Institute',
  'Government Sangeet Mahavidyalaya',
  'IPS Academy',
  'Shri Jain Sangeet Mahavidyalaya',
  'Shri Krishna Sangeet Mahavidyalaya',
  'Shubhankan Fine Arts College',
  'Venkateshwar Institute of Technology',
  'Sri Satya Sai Pharmacy Research Institute',
  'Acropolis Institute of Pharmaceutical Eduction and Research',
  'Subhdeep College of Pharmacy',
  'Arihant College of Paramedical Science',
  'MIBE Graguate School for Nurses',
  'School of Computer and Electronics',
  'Astral Institute of Technology and Research',
  'BM College of Technology',
  'Chamelidevi Institute of Technology and Management',
  'Jagadguru Dattatray College of Technology',
  'KC Bansal Technical Institute',
  'Lord Krishna College of Technology',
  'Mahatma Gandhi Institute of Engineering and Management',
  'Mathura Devi Institute of Technology and Management',
  'Oriental Institute of Science and Technology',
  'Patel College of Science and Technology',
  'Prestige Institute of Engineering and Science',
  'Priyatam Institute of Technology and Science',
  'Royal College of Techonology',
  'RKDF School of Engineering',
  'Sanghavi Innovative Academy (SIA)',
  'Shiv Kumar Singh Institute of Technology and Science',
  'Truba Institute of Engineering and Information Technology',
  'Vikrant Institute of Technology and Management',
  'Vindhya Institute of Technology and Science',
  'Star Academy of Technology and Management',
  'Government Nirbhai Singh Patel Navin Science College',
  'Government Nursing College',
  'PMB Gujarati Arts Mahavidhyalaya',
  'Devi Ahilya Arts and Commerce Mahavidyalaya',
  'Devi Ahilya Mateshwari Suganidevi Girls College',
  'Rukama Devi Pannalal Laddha Maheshwari Commerce Mahavidyalaya',
  'Imperial College of Professional Studies',
  'Pria Darshani Mahavidyalaya',
  'Study Institute of Management',
  'Tagore Mahavidyalaya',
  'Kothari College Management Science and Technology',
  'Mata Gujri Girls College of Professional Education',
  'Swati Jain Institute of Management Studies',
  'Al Farooque Unani Tibbia College',
  'Indore Institute of Medical Sciences and Technology',
  'Jhalwa Commerce and Science College',
  'Saint Deewan Karamchand Girls College',
  'Vidya Sagar Mahavidyalaya',
  'Sanskar College of Professional Studies',
  'Softvision Institute of Technology and Science',
  'Maharishi Institute of Management',
  'PMT of MP (Devi Ahilya College of Paramedical Sciences)',
  'Shubhdeep Ayurved Medical College & Hospital',
  'Acharya Gyan Ayurved Mahavidyalaya',
  'Campfeedars Technically Training Institute',
  'Renaissance College of Commerce and Management',
  'Shri Cloth Market Institute of Professional Studies',
  'Shri Gujarati Samaj Innovative College of Commerce & Science',
  'CH Institute of Management and Commerce',
  'Neelgiri College of Professional Studies',
  'Choithram College of Professional studies',
  'Duba College of Engenring and Technology',
  'Matushri Ahilya Devi Institute of Management and Research',
  'Choithram College of Paramedical Science',
  'Patel College of Management',
  'Vidhya Institute of Technology',
  'RKDF College of Technology',
  'Safe Institute of Nursing College',
  'Victoria College of Education',
  'Index Nursing College',
  'Indore Nursing College',
  'SDPS College of Nursing',
  'Amaltash Institute of Professionl Studies',
  'Arihant College',
  'Shri Gujrati Samaj B Ed College',
  'Central College of Education',
  'Kk Science and Mahavidyalaya Professional Studies',
  'Eni Besent College',
  'Victoria College',
  'RD Memorial College of Nursing',
  'Acropolis Institute of Management Studies and Research',
  'Shri Umiya Kanya Mahavidyalaya',
  'Bombay Hospital College of Nursing',
  'Guru Gobind Singh Institute of Technology and Management (GGSITM)',
  'Sahib Institute of Management and Research',
  'BM College of Management and Research',
  'Arihant Institute of Management Studies',
  'Modern Institute of Professional Studies',
  'I-sect College of Professional Studies',
  'Akshay Academy College',
  'Indore Management Institute',
  'Vikrant Institute of Intigrated BBA and Advancce Studies',
  'Radiant Institute of Management and science',
  'Sri Aurobindo Institute of Management',
  'Swami Vivekanand Group of College',
  'Gyanoday Mahavidyalaya',
  'Amaltas College of Management',
  'Central College of Professional Studies',
  'Indore Institute of Computer Application',
  'Sapient Institute of Management Studies',
  'Transnational Knowledge Society Group of Institute Faculity of Management',
  'Vindhya Institute of Management and Research',
  'Tagore Institute of Management and Studies',
  'Central India Institute of Technology and Management',
  'CH Institute of Management',
  'Pioneer Institute of Management and Research',
  'Lakshami Narayan College of Technology and Management',
  'Malwa Institute of Technology',
  'Venkateshwar Institute of Management',
  'Sahib Institute of Management',
  'Sri Vaishnav Prabandh Sansthan',
  'IPS Group of Institution',
  'Vidyasagar Institute of Technology',
  'Indore Institute of Management and Research',
  'Industrial Training Institute (ITI Women)',
  'Vidya Sagar BEd College',
  'AGM Group of Institutions',
  'Daly College',
  'State Institute of Hotel Management',
  'Madhya Pradesh Professors Association',
  'Mathuradevi Institute of Technology and Management',
  'Oriental University',
  'Ilva Commerce and Science College',
  'Sys College',
  'Vaidehi College',
  'Govt Sanskrit College',
  'UGC DAE Consortium for Scientific Research',
  'Maharaja Group of Institutions',
  'Govt District Institute of Education and Training Bijalpur',
  'Priyadarshini Mahavidyalaya',
  'Vidhyasagar College',
  'Tagore Shiksha Mahavidyalaya',
  'Indore Glorious Education College',
  'AISECT College',
  'Parijat Vidya Niketan Samiti',
  'Shakuntala Devi DEd College Palasia',
  'Bal Niketan Sangh',
  'Gyanodaya Mahavidyalaya',
  'Pragya College Bhicholi Mardana',
  'Shiva College of Education Gari Piplia',
  'Askhay Academy College of Eucation',
  'DC University (DCU)',
  'Symbiosis University of Applied Sciences (SUAS)',
  'Smt Rukhminiben Deepchand Bhai Gardi Nurses Training Centre',
  'Malwa Polytechnic Pharmacy College',
  'Raja Ramanna Centre for Advanced Technology (RRCAT)',
  'Government Women Polytechnic College',
  'National Institute of Construction Management and Research (NICMAR)',
  'Lal Bahadur Shastri Institute of Technology and Management (LBSITM)',
  'Shri Atal Bihari Vajpai Govt Arts And Commerce College',
  'C-DAC (Centre for Development of Advanced Computing)',
  'Modern Institute of Medical Sciences (MIMS)',
  'Medicaps University',
  'Shri Vaishnav Vidyapeeth University',
  'Annie Instittute of Technology and Research Centre',
  'Indore Indira Institute of Business Management',
  'Malwa Institute of Management',
  'Mandsaur Institute of Technology (MIT)',
  'Mathuradevi Institute of Management',
  'Shreejee Institute of Technology and Management',
  'Shri Vaishnav Institute of Pharmacy (SVITS)',
  'Shri Vaishnav Institute of Architecture (SVIA)',
];
export const parties = [
  '2010 Peace Party',
  'Alaskan Independence Party',
  'American Independent (CA)',
  'Conservative Party',
  'Constitution Party',
  'Democratic Party',
  'Green Party',
  'Independence Party of America',
  'Independent (No party affiliation)',
  'Independent American (Nevada)',
  'Justice for Vermonters Party',
  'Libertarian Party',
  'Liberty Union Party',
  'Moderate Party',
  'Mountain Party',
  'Peace and Freedom Party',
  'Progressive Democratic Party',
  'Progressive Party (Vermont)',
  'Vermont-Independence Party',
  'Reform Party',
  'Republican Party',
  'Tea Party',
  'Working Families Party',
];
export const titles = [
  'College Student Representative',
  'Department Representative',
  'Student Body Head',
  'Student Coordinator',
];
export const Names = [
  'Maia',
  'Asher',
  'Olivia',
  'Atticus',
  'Amelia',
  'Jack',
  'Charlotte',
  'Theodore',
  'Isla',
  'Oliver',
  'Isabella',
  'Jasper',
  'Cora',
  'Levi',
  'Violet',
  'Arthur',
  'Mia',
  'Thomas',
  'Elizabeth',
  'Liam',
  'Noah',
  'Oliver',
  'Elijah',
  'James',
  'William',
  'Benjamin',
  'Lucas',
  'Henry',
  'Theodore',
  'Jack',
  'Levi',
  'Alexander',
  'Jackson',
  'Mateo',
  'Daniel',
  'Michael',
  'Mason',
  'Sebastian',
  'Ethan',
  'Logan',
  'Owen',
  'Samuel',
  'Jacob',
  'Asher',
  'Aiden',
  'John',
  'Joseph',
  'Wyatt',
  'David',
  'Leo',
  'Luke',
  'Julian',
  'Hudson',
  'Grayson',
  'Matthew',
  'Ezra',
  'Gabriel',
  'Carter',
  'Isaac',
  'Jayden',
  'Luca',
  'Anthony',
  'Dylan',
  'Lincoln',
  'Thomas',
  'Maverick',
  'Elias',
  'Josiah',
  'Charles',
  'Caleb',
  'Christopher',
  'Ezekiel',
  'Miles',
  'Jaxon',
  'Isaiah',
  'Andrew',
  'Joshua',
  'Nathan',
  'Nolan',
  'Adrian',
  'Cameron',
  'Santiago',
  'Eli',
  'Aaron',
  'Ryan',
  'Angel',
  'Cooper',
  'Waylon',
  'Easton',
  'Kai',
  'Christian',
  'Landon',
  'Colton',
  'Roman',
  'Axel',
  'Brooks',
  'Jonathan',
  'Robert',
  'Jameson',
  'Ian',
  'Everett',
  'Greyson',
  'Wesley',
  'Jeremiah',
  'Hunter',
  'Leonardo',
  'Jordan',
  'Jose',
  'Bennett',
  'Silas',
  'Nicholas',
  'Parker',
  'Beau',
  'Weston',
  'Austin',
  'Connor',
  'Carson',
  'Dominic',
  'Xavier',
  'Jaxson',
  'Jace',
  'Emmett',
  'Adam',
  'Declan',
  'Rowan',
  'Micah',
  'Kayden',
  'Gael',
  'River',
  'Ryder',
  'Kingston',
  'Damian',
  'Sawyer',
  'Luka',
  'Evan',
  'Vincent',
  'Legend',
  'Myles',
  'Harrison',
  'August',
  'Bryson',
  'Amir',
  'Giovanni',
  'Chase',
  'Diego',
  'Milo',
  'Jasper',
  'Walker',
  'Jason',
  'Brayden',
  'Cole',
  'Nathaniel',
  'George',
  'Lorenzo',
  'Zion',
  'Luis',
  'Archer',
  'Enzo',
  'Jonah',
  'Thiago',
  'Theo',
  'Ayden',
  'Zachary',
  'Calvin',
  'Braxton',
];
